import type { Metadata } from 'next'
import './globals.css'
import { Navbar } from '@/component/navigation/Navbar'
import { Footer } from '@/component/common/Footer'
import { jost } from './font'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
